### ISSUE TITLE
SSR errors w/ intersection observer

### ISSUE THREAD

**Issue by brandonmp** [GraphCMS/graphcms-image#1]
I was trying to test this out w/ my nextjs project, but I keep running up against this error:

```
ReferenceError: window is not defined
    at Object.<anonymous> (/mnt/c/Users/brand/code/admitbrain/node_modules/intersection-observer/intersection-observer.js:724:3)
    at Module._compile (module.js:641:30)
    at Module._compile (/mnt/c/Users/brand/code/admitbrain/node_modules/source-map-support/source-map-support.js:492:25)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/mnt/c/Users/brand/code/admitbrain/node_modules/graphcms-image/index.js:7:1)
    at Module._compile (module.js:641:30)
    at Module._compile (/mnt/c/Users/brand/code/admitbrain/node_modules/source-map-support/source-map-support.js:492:25)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/mnt/c/Users/brand/code/admitbrain/components/Image/Image.js:5:1)
    at Module._compile (module.js:641:30)
    at Module._compile (/mnt/c/Users/brand/code/admitbrain/node_modules/source-map-support/source-map-support.js:492:25)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/mnt/c/Users/brand/code/admitbrain/.next/dist/components/Image/index.js:7:14)
    at Module._compile (module.js:641:30)
    at Module._compile (/mnt/c/Users/brand/code/admitbrain/node_modules/source-map-support/source-map-support.js:492:25)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/mnt/c/Users/brand/code/admitbrain/pages/blog-post-template.js:17:1)
    at Module._compile (module.js:641:30)
    at Module._compile (/mnt/c/Users/brand/code/admitbrain/node_modules/source-map-support/source-map-support.js:492:25)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at _callee$ (/mnt/c/Users/brand/code/admitbrain/node_modules/next/dist/server/require.js:33:46)
    at tryCatch (/mnt/c/Users/brand/code/admitbrain/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/mnt/c/Users/brand/code/admitbrain/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:299:22)
    at Generator.prototype.(anonymous function) [as next] (/mnt/c/Users/brand/code/admitbrain/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/mnt/c/Users/brand/code/admitbrain/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /mnt/c/Users/brand/code/admitbrain/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous>
```

I'm calling it in my code via:
```
const Image = (props: Props) =>
    typeof window !== 'undefined'
      && <div
              style={{
                  position: 'relative',
                  minHeight: 500,
                  maxWidth: 600
              }}
          >
              <GraphImage
                  image={props.image}
                  alt={props.alt}
                  maxWidth={600}
              />
          </div>
```

The error only throws on the server, and the image appears to load fine once in the client.

**Comment by hmeissner** [comment]
Hey @brandonmp, thanks for reporting this! I'll be working on making the component fully support SSR in the upcoming days
